on: push
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: "recursive"
          fetch-depth: "0"
      - name: esp-idf build
        uses: espressif/esp-idf-ci-action@main
        with:
          command: git config --global --add safe.directory /app && git describe --tags && idf.py -C ./subdir build
