on: push
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: "recursive"
          fetch-depth: "0"
      - name: esp-idf build
        uses: AerofoilsGmbH/esp-idf-ci-action@additional-args
        with:
          extra_docker_args: -v ./.ccache:/root/.ccache -e CCACHE_DIR=/root/.ccache
          esp_idf_docker_image: kumekay/idf
          esp_idf_version: v5.3.1
          path: subdir
